
services:
  baseball-app:
    build: .
    ports:
      - "80:3000"
    volumes:
      - ./data:/app/data  # Persist data files on host
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3